function[RowShifts,ColumnShifts,OrderedVolumes] = OrderVolumes(...
    tvector,Size,BlurFactor,red_vol)
    
    for t=tvector
        stackFixed(:,:,ceil(Size(3)/2)) = imgaussfilt(...
            red_vol(:,:,ceil(Size(3)/2),t),BlurFactor);
        RowShifts(ceil(Size(3)/2),t) = 0;
        ColumnShifts(ceil(Size(3)/2),t) = 0;

        for i=1:ceil(Size(3)/2)-1 % XXX [Fix]: ending index
            output = dftregistrationAlex(...
                fft2(imgaussfilt(stackFixed(:,:,min(ceil(Size(3)/2),...
                ceil(Size(3)/2)-i+5)),BlurFactor)),...
                fft2(imgaussfilt(red_vol(:,:,ceil(Size(3)/2)-i,t),...
                BlurFactor)),10);
            row_shift = output(1);
            column_shift = output(2);
            stackFixed(:,:,ceil(Size(3)/2)-i) = imtranslate(...
                imgaussfilt(red_vol(:,:,ceil(Size(3)/2)-i,t),...
                BlurFactor), [column_shift row_shift]);
            RowShifts(ceil(Size(3)/2)-i,t) = row_shift;
            ColumnShifts(ceil(Size(3)/2)-i,t) = column_shift;
        end

        for(i=1:ceil(Size(3)/2)-1)
            output = dftregistrationAlex(fft2(imgaussfilt(stackFixed(...
                :,:,max(ceil(Size(3)/2),i-5+ceil(Size(3)/2))),...
                BlurFactor)),...
                fft2(imgaussfilt(red_vol(:,:,i+ceil(Size(3)/2),t),...
                BlurFactor)),10);
            row_shift = output(1);
            column_shift = output(2); %XXX
%             stackFixed(:,:,i+ceil(Size(3)/2)) = imtranslate(...
%                 red_vol(:,:,i+ceil(Size(3)/2),t),[column_shift row_shift]);
            stackFixed(:,:,i+ceil(Size(3)/2)) = imtranslate(...
                imgaussfilt(red_vol(:,:,i+ceil(Size(3)/2),t),...
                BlurFactor),[column_shift row_shift]);
            RowShifts(i+ceil(Size(3)/2),t) = row_shift;
            ColumnShifts(i+ceil(Size(3)/2),t) = column_shift;
        end
        OrderedVolumes(:,:,:,t) = stackFixed;
    end
end